N_ACTIONS = 11
LEARNING_RATE = 0.00001
BATCH_SIZE = 32
N_FRAMES = 1
N_EPISODES = 200
MAX_STEPS_PER_EPISODE = 50
CHECKPOINT_FREQ = 5          # episodes
CHECKPOINT_DIR =   "artifacts/rlhf"
START_CHECKPOINT = "/Users/cjryan/Desktop/MATH4025-Minecraft-Project/artifacts/rlhf/grandiose-zebra-391/checkpoint_02.15.02.04.2026.pt"
N_REWARD_EPOCHS = 10
N_PREF_ITERATIONS = 10 # the number of preferences that will be generated for each reward epoch
N_REWARD_STEPS = 5 # the number of steps that the reward model will be optimized
N_RL_STEPS = 100
POLICY_LR = 0.0001
REWARD_MODEL_LR = 0.00001
PPO_EPOCHS = 4
PPO_CLIP = 0.1
PPO_GAMMA = 0.99
PPO_LAMBDA = 0.95
VALUE_COEF = 0.1
ENTROPY_COEF = 0.05
PPO_LR = 0.00005
N_PPO_ROLLOUTS = 50
MAX_ITERATIONS = 100
N_POLICY_LAYERS = 4
N_VALUE_NET_LAYERS = 2
ENV_RESET_INTERVAL = 20
ENV_RETRY_ATTEMPTS = 5    # how many times to retry creating a new environment before giving up
ENV_RETRY_DELAY = 10      # seconds to wait between retry attempts